// src/components/allFonts.ts
export interface FontOption {
  id: number;
  styleId: number; // Step5'te seçilen style id
  fontFamily: string;
  previewImg: string;
  displayName: string;
  file: string;
}

export const allFonts: FontOption[] = [
  // ================= CLASSIC (styleId: 1) =================
  {
    id: 1,
    styleId: 1,
    fontFamily: "Verace",
    displayName: "Verace",
    previewImg: "/images/app/font/moder.svg",
    file: "/fonts/modern/verace/verace-medium.otf",
  },
   {
    id: 2,
    styleId: 1,
    fontFamily: "Verace",
    displayName: "Verace",
    previewImg: "/images/app/font/moder.svg",
    file: "/fonts/modern/verace/verace-medium.otf",
  },

  // ================= RETRO (styleId: 2) =================
  {
    id: 4,
    styleId: 2,
    fontFamily: "RetroFont1",
    displayName: "Retro Style 1",
    previewImg: "/images/app/font/font2.svg",
    file: "/fonts/retro/retro1.otf",
  },
  {
    id: 5,
    styleId: 2,
    fontFamily: "RetroFont2",
    displayName: "Retro Style 2",
    previewImg: "/images/app/font/font2.svg",
    file: "/fonts/retro/retro2.otf",
  },

  // ================= MODERN (styleId: 3) =================
  {
    id: 6,
    styleId: 3,
    fontFamily: "ModernFont1",
    displayName: "Modern Style 1",
    previewImg: "/images/app/font/font3.svg",
    file: "/fonts/modern/modern1.ttf",
  },
  {
    id: 7,
    styleId: 3,
    fontFamily: "ModernFont2",
    displayName: "Modern Style 2",
    previewImg: "/images/app/font/font3.svg",
    file: "/fonts/modern/modern2.ttf",
  },

  // ================= FUNKY (styleId: 4) =================
  {
    id: 8,
    styleId: 4,
    fontFamily: "FunkyFont1",
    displayName: "Funky Style 1",
    previewImg: "/images/app/font/font4.svg",
    file: "/fonts/funky/funky1.otf",
  },
  {
    id: 9,
    styleId: 4,
    fontFamily: "FunkyFont2",
    displayName: "Funky Style 2",
    previewImg: "/images/app/font/font4.svg",
    file: "/fonts/funky/funky2.otf",
  },

  // ================= HANDWRITTER (styleId: 5) =================
{
  id: 10,
  styleId: 5,
  fontFamily: "Agezka",
  displayName: "Agezka",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/agezka/agezka.otf",
},
{
  id: 11,
  styleId: 5,
  fontFamily: "Alena",
  displayName: "Alena",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/alena/alena.otf",
},
{
  id: 12,
  styleId: 5,
  fontFamily: "Asgilla",
  displayName: "Asgilla",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/asgilla/asgilla.otf",
},
{
  id: 13,
  styleId: 5,
  fontFamily: "Avliana",
  displayName: "Avliana",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/avliana/avliana.otf",
},
{
  id: 14,
  styleId: 5,
  fontFamily: "Beatina",
  displayName: "Beatina",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/beatina/beatina.otf",
},
{
  id: 15,
  styleId: 5,
  fontFamily: "Beautiful",
  displayName: "Beautiful",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/beautiful/beautiful.ttf",
},
{
  id: 16,
  styleId: 5,
  fontFamily: "Bicers",
  displayName: "Bicers",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/bicers/bicers.otf",
},
{
  id: 17,
  styleId: 5,
  fontFamily: "Birjhon",
  displayName: "Birjhon",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/birjhon/birjhon.otf",
},
{
  id: 18,
  styleId: 5,
  fontFamily: "Bistro",
  displayName: "Bistro",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/bistro/bistro.otf",
},
{
  id: 19,
  styleId: 5,
  fontFamily: "Brasskent",
  displayName: "Brasskent",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/brasskent/brasskent.otf",
},
{
  id: 20,
  styleId: 5,
  fontFamily: "Broken",
  displayName: "Broken",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/broken/broken.otf",
},
{
  id: 21,
  styleId: 5,
  fontFamily: "Brownie",
  displayName: "Brownie",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/brownie/brownie.otf",
},
{
  id: 22,
  styleId: 5,
  fontFamily: "Bumgreks",
  displayName: "Bumgreks",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/bumgreks/bumgreks.otf",
},
{
  id: 23,
  styleId: 5,
  fontFamily: "Cabosunset",
  displayName: "Cabosunset",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/cabosunset/cabosunset.otf",
},
{
  id: 24,
  styleId: 5,
  fontFamily: "Canessa",
  displayName: "Canessa",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/canessa/canessa.otf",
},
{
  id: 25,
  styleId: 5,
  fontFamily: "Chapney",
  displayName: "Chapney",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/chapney/chapney.otf",
},
{
  id: 26,
  styleId: 5,
  fontFamily: "Chillyot",
  displayName: "Chillyot",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/chillyot/chillyot.otf",
},
{
  id: 27,
  styleId: 5,
  fontFamily: "Country",
  displayName: "Country",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/country/country.otf",
},
{
  id: 28,
  styleId: 5,
  fontFamily: "Creftins",
  displayName: "Creftins",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/creftins/creftins.otf",
},
{
  id: 29,
  styleId: 5,
  fontFamily: "Elvellon",
  displayName: "Elvellon",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/elvellon/elvellon.otf",
},
{
  id: 30,
  styleId: 5,
  fontFamily: "Flower",
  displayName: "Flower",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/flower/flower.otf",
},
{
  id: 31,
  styleId: 5,
  fontFamily: "Gestclo",
  displayName: "Gestclo",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/gestclo/gestclo.otf",
},
{
  id: 32,
  styleId: 5,
  fontFamily: "History-Birthday",
  displayName: "History-Birthday",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/history-birthday/history-birthday.otf",
},
{
  id: 33,
  styleId: 5,
  fontFamily: "Katie-Ginger",
  displayName: "Katie-Ginger",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/katie-ginger/katieginger.otf",
},
{
  id: 34,
  styleId: 5,
  fontFamily: "klaty-lotleg",
  displayName: "klaty-lotleg",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/klaty-lotleg/klaty-lotleg.otf",
},
{
  id: 35,
  styleId: 5,
  fontFamily: "Liquid",
  displayName: "Liquid",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/liquid/liquid.otf",
},
{
  id: 36,
  styleId: 5,
  fontFamily: "Luce",
  displayName: "Luce",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/luce/luce.ttf",
},
{
  id: 37,
  styleId: 5,
  fontFamily: "Lunar",
  displayName: "Lunar",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/lunar/lunar.otf",
},
{
  id: 38,
  styleId: 5,
  fontFamily: "Luxes",
  displayName: "Luxes",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/luxes/luxes.otf",
},
{
  id: 39,
  styleId: 5,
  fontFamily: "Luxurio",
  displayName: "Luxurio",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/luxurio/luxurio.otf",
},
{
  id: 40,
  styleId: 5,
  fontFamily: "Maisonelle",
  displayName: "Maisonelle",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/maisonelle/maisonelle.otf",
},
{
  id: 41,
  styleId: 5,
  fontFamily: "Mandalica",
  displayName: "Mandalica",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/mandalica/mandalica.otf",
},
{
  id: 42,
  styleId: 5,
  fontFamily: "Margareth",
  displayName: "Margareth",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/margareth/margareth.otf",
},
{
  id: 43,
  styleId: 5,
  fontFamily: "Matcha",
  displayName: "Matcha",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/matcha/matcha.otf",
},
{
  id: 44,
  styleId: 5,
  fontFamily: "Mayren",
  displayName: "Mayren",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/mayren/mayren.otf",
},
{
  id: 45,
  styleId: 5,
  fontFamily: "Melonica",
  displayName: "Melonica",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/melonica/melonica.otf",
},
{
  id: 46,
  styleId: 5,
  fontFamily: "Mildon",
  displayName: "Mildon",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/mildon/mildon.otf",
},
{
  id: 47,
  styleId: 5,
  fontFamily: "Montege",
  displayName: "Montege",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/montege/montege.otf",
},
{
  id: 48,
  styleId: 5,
  fontFamily: "Morey",
  displayName: "Morey",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/morey/morey.otf",
},
{
  id: 49,
  styleId: 5,
  fontFamily: "Morisa",
  displayName: "Morisa",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/morisa/morisa.otf",
},
{
  id: 50,
  styleId: 5,
  fontFamily: "Murces",
  displayName: "Murces",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/murces/murces.otf",
},
{
  id: 51,
  styleId: 5,
  fontFamily: "Nilfgard",
  displayName: "Nilfgard",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/nilfgard/nilfgard.otf",
},
{
  id: 52,
  styleId: 5,
  fontFamily: "Nirain",
  displayName: "Nirain",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/nirain/nirain.otf",
},
{
  id: 53,
  styleId: 5,
  fontFamily: "Noira",
  displayName: "Noira",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/noira/noira.otf",
},
{
  id: 54,
  styleId: 5,
  fontFamily: "Paladin",
  displayName: "Paladin",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/paladin/paladin.otf",
},
{
  id: 55,
  styleId: 5,
  fontFamily: "Palm",
  displayName: "Palm",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/palm/palm.otf",
},
{
  id: 56,
  styleId: 5,
  fontFamily: "Panera",
  displayName: "Panera",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/panera/panera.otf",
},
{
  id: 57,
  styleId: 5,
  fontFamily: "Pattas",
  displayName: "Pattas",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/pattas/pattas.otf",
},
{
  id: 58,
  styleId: 5,
  fontFamily: "Qaugherty",
  displayName: "Qaugherty",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/qaugherty/qaugherty.ttf",
},
{
  id: 59,
  styleId: 5,
  fontFamily: "Resika",
  displayName: "Resika",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/resika/resika.otf",
},
{
  id: 60,
  styleId: 5,
  fontFamily: "Rofina",
  displayName: "Rofina",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/rofina/rofina.otf",
},
{
  id: 61,
  styleId: 5,
  fontFamily: "Ronaldtumb",
  displayName: "Ronaldtumb",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/ronaldtumb/ronald-tumb.otf",
},
{
  id: 62,
  styleId: 5,
  fontFamily: "Roselia",
  displayName: "Roselia",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/roselia/roselia.otf",
},
{
  id: 63,
  styleId: 5,
  fontFamily: "Rovale",
  displayName: "Rovale",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/rovale/rovale.otf",
},
{
  id: 64,
  styleId: 5,
  fontFamily: "Rustic",
  displayName: "Rustic",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/rustic/rustic.otf",
},
{
  id: 65,
  styleId: 5,
  fontFamily: "Sanita",
  displayName: "Sanita",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/sanita/sanita.otf",
},
{
  id: 66,
  styleId: 5,
  fontFamily: "Semestha",
  displayName: "Semestha",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/semestha/semestha.otf",
},
{
  id: 67,
  styleId: 5,
  fontFamily: "Sepia",
  displayName: "Sepia",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/sepia/sepia.otf",
},
{
  id: 68,
  styleId: 5,
  fontFamily: "Seraphy",
  displayName: "Seraphy",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/seraphy/seraphy.otf",
},
{
  id: 69,
  styleId: 5,
  fontFamily: "Sergioromeo",
  displayName: "Sergioromeo",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/sergioromeo/sergio-romeo.otf",
},
{
  id: 70,
  styleId: 5,
  fontFamily: "Shilven",
  displayName: "Shilven",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/shilven/shilven.otf",
},
{
  id: 71,
  styleId: 5,
  fontFamily: "Sloovia",
  displayName: "Sloovia",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/sloovia/sloovia.otf",
},
{
  id: 72,
  styleId: 5,
  fontFamily: "Weekend",
  displayName: "Weekend",
  previewImg: "/images/app/font/font5.svg",
  file: "/fonts/handwritter/weekend/weekend.otf",
},

  // ================= MINIMAL (styleId: 6) =================
  {
    id: 12,
    styleId: 6,
    fontFamily: "PlayfulFont1",
    displayName: "Playful Style 1",
    previewImg: "/images/app/font/font6.svg",
    file: "/fonts/playful/playful1.otf",
  },
  {
    id: 13,
    styleId: 6,
    fontFamily: "PlayfulFont2",
    displayName: "Playful Style 2",
    previewImg: "/images/app/font/font6.svg",
    file: "/fonts/playful/playful2.otf",
  },

  // ================= FUTURE (styleId: 7) =================
  {
    id: 14,
    styleId: 7,
    fontFamily: "Orbitron",
    displayName: "Orbitron",
    previewImg: "/images/app/font/font7.svg",
    file: "/fonts/futuristic/orbitron/orbitron.ttf",
  },
  {
    id: 15,
    styleId: 7,
    fontFamily: "TechFont2",
    displayName: "Tech Style 2",
    previewImg: "/images/app/font/font7.svg",
    file: "/fonts/tech/tech2.ttf",
  },

  // ================= LUXURY (styleId: 8) =================
  {
    id: 16,
    styleId: 8,
    fontFamily: "LuxuryFont1",
    displayName: "Luxury Style 1",
    previewImg: "/images/app/font/font8.svg",
    file: "/fonts/luxury/luxury1.otf",
  },
  {
    id: 17,
    styleId: 8,
    fontFamily: "LuxuryFont2",
    displayName: "Luxury Style 2",
    previewImg: "/images/app/font/font8.svg",
    file: "/fonts/luxury/luxury2.ttf",
  },
];